name: "GitModule Tracker"

on:
  workflow_dispatch:
    inputs:
      resourceGroupName:
        type: string
        description: "Resource Group where infrastructure will be deployed/updated"
        required: true
        default: ""
      subscriptionId:
        type: string
        description: "Subscription Id where infrastructure will be deployed/updated"
        required: true
        default: ""
      functionAppName:
        type: string
        description: "Function App where code will be deployed/updated"
        required: true
        default: ""

jobs:
  deploy_dashboard:
    runs-on: ubuntu-latest
    name: "Module tracker Backend"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_JS_SUB }}
          enable-AzPSSession: true
      - name: "Deploy infrastructure"
        id: infratracker
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ github.event.inputs.subscriptionId }}
          resourceGroupName: ${{ github.event.inputs.resourceGroupName }}
          template: ./hackaton/azure/infra.bicep
      - name: "Deploy code"
        shell: pwsh
        run: |
          # Initialize parameters
          Install-Module -Name Az.Functions -Force
          # Create a Zip with the publish result
          Remove-Item -Path ./hackaton/azure/infra.bicep
          $publishFolder = "hackaton/azure"
          $publishZip = "publish.zip"
          Add-Type -assembly "system.io.compression.filesystem"
          [io.compression.zipfile]::CreateFromDirectory($publishFolder, $publishZip)
          az account set -s ${{ github.event.inputs.subscriptionId }}
          az functionapp deployment source config-zip -g ${{ github.event.inputs.resourceGroupName }} -n ${{ github.event.inputs.functionAppName }} --src $publishZip
