name: test
on:
  workflow_dispatch:
    inputs:
        ReleaseTag:
          type: string
          description: Release tag you want to scan for.
          required: false
          
        StorageAccountName:
          type: string
          description: Name of the storage account where the hash file will be stored in.
          required: true
          default: carmlhack2022
          
        StorageAccountContainerName:
          type: string
          description: Name of the storage container where the hash file will be stored in.
          required: true
          default: carml-releases
          
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo        
        uses: actions/checkout@v2
        
      - name: Run Publish-VersionHash.ps1
        shell: pwsh
        env:
          STG_SAS_TOKEN: ${{ secrets.STG_SAS_TOKEN }}
        run: |
          Install-Module -Name Az.Storage -Force
          ./hackaton/azure/Publish-VersionHash.ps1 -ReleaseTag "${{inputs.ReleaseTag}}" -StorageAccountName "${{inputs.StorageAccountName}}" -StorageAccountContainerName "${{inputs.StorageAccountContainerName}}" -StorageAccountSasToken "${{ env.STG_SAS_TOKEN }}"
